version: '3'
services:

  nginx_proxy:
    image: xcgd/nginx-vts
    ports:
      - 80:80
    volumes:
      - ./configs:/etc/nginx
    restart: unless-stopped

  test_server:
    build:
      context: https://github.com/3kybika/TP_highload__hw2.git#:backend_servers
    restart: unless-stopped
    ports:
      - 81:81
    container_name: test_server
    command: "./start.sh"
    
  cadvisor-exporter:
    image: google/cadvisor
    ports:
      - 9000:8080
    restart: unless-stopped
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
          
  prodvtsexporter:
    image: sophos/nginx-vts-exporter
    container_name: prodvtsexporter
    restart: unless-stopped
    environment:
      NGINX_STATUS: "http://nginx_proxy:9913/status/format/json"
    restart: unless-stopped
    expose:
      - 9113
    ports:
      - 9113:9113
