version: '3'
services:
  server:
    build:
      context: https://github.com/3kybika/TP_highload__hw2.git#:backend_servers
    restart: unless-stopped
    container_name: test_server
    ports:
      - 80:80
    command: "./start.sh"
  cadvisor-exporter:
    image: google/cadvisor
    ports:
      - 9000:8080
    restart: unless-stopped
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
  nginx_exporter:
    image: fish/nginx-exporter
    command:
    - 'nginx.scrape_uri=http://test_server:80/nginx_status'    
