version: '3'
services:

  nginx_proxy:
    image: xcgd/nginx-vts
    ports:
      - 80:80
      - 8080:9913
    volumes:
      - ./configs:/etc/nginx
    restart: unless-stopped

  test_server:
    build:
      context: https://github.com/3kybika/TP_highload__hw2.git#:backend_servers
    restart: unless-stopped
    container_name: test_server
    ports:
      - 81:81
    command: "./start.sh"
    
  cadvisor-exporter:
    image: google/cadvisor
    ports:
      - 9000:8080
    restart: unless-stopped
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
          
  prodvtsexporter:
    image: sophos/nginx-vts-exporter
    container_name: prodvtsexporter
    restart: unless-stopped
    environment:
      - NGINX_HOST = http://nginx_proxy:8080/vhost_status/format/json
    restart: unless-stopped
    expose:
      - 9913
    ports:
      - 9913:9913
